import { ScaledSheet } from "react-native-size-matters";
import { Metricstablet, FontsTablet, Colors } from '../../../Theme/';
const TEXT_BTN = FontsTablet.style.normal;
export default ScaledSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: Colors.backgroundSecondary,
  },
  container: {
    paddingBottom: Metricstablet.baseMargin,
    paddingHorizontal: Metricstablet.doubleBaseMargin,
  },
  logo: {
    height: Metricstablet.screenHeight * 0.22,
    width: '100%',
    alignItems: 'center',
  },
  headerLogo: {
    resizeMode: 'stretch',
    position: 'relative',
    height: Metricstablet.screenHeight / 7,
    width: Metricstablet.screenWidth / 3,
    alignSelf: 'center',
    marginBottom: Metricstablet.doubleBaseMargin * 2,
  },
  centered: {
    alignItems: 'center',
  },
  headerContainer: {
    paddingTop: Metricstablet.doubleBaseMargin * 3,
    height: Metricstablet.screenHeight * 0.37,
    width: '100%',
    paddingHorizontal: "20@ms",
  },
  header: {
    alignSelf: 'center',
    flex: 0.5,
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: Metricstablet.baseMargin,
  },
  headerText: {
    color: Colors.black,
    backgroundColor: Colors.transparent,
    alignSelf: 'center',
    textAlign: 'center',
    marginTop: "10@vs",
    ...FontsTablet.style.normal,
  },
  TextInputStyleClass: {
    textAlign: 'center',
    color: Colors.snow,
    flex: 1,
    alignSelf: 'stretch',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    marginLeft: "20@ms",
    marginRight: "20@ms",
  },
  Footer: {
    marginBottom: Metricstablet.baseMargin * 5,
  },
  cguContainer: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: Metricstablet.baseMargin,
    flex: 0.8,
  },
  checkboxContainer: {
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: Metricstablet.baseMargin,
    width: '90%',
  },
  conditionsPwd: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: "4@ms0.3",
    borderWidth: 1,
    borderColor: 'transparent',
    paddingBottom: "10@ms",
    paddingTop: "10@ms",
    marginLeft: "40@vs",
    marginRight: "20@vs",
    alignItems: 'flex-start',
    marginBottom: Metricstablet.baseMargin,
    width: '70%',
  },
  cguText: {
    alignSelf: 'stretch',
    color: Colors.snow,
    ...FontsTablet.style.normal,
  },
  cguLink: {
    alignSelf: 'flex-end',
    width: '100%',
    color: '#ec008c',
    textDecorationLine: 'underline',
    ...FontsTablet.style.normal,
  },
  btnPressed: {
    width: '48%',
  },
  btnUnpressed: {
    width: '48%',
    backgroundColor: Colors.snow,
  },
  textStyleBtn1: {
    color: Colors.lightBlue,
    fontWeight: '400',
    ...TEXT_BTN,
  },
  textStyleBtn2: {
    fontWeight: '400',
    ...TEXT_BTN,
  },
  dateText: {
    color: Colors.snow,
    backgroundColor: Colors.transparent,
    alignSelf: 'center',
    textAlign: 'left',
    marginTop: "10@ms",
    marginLeft: "-150@ms",
    ...FontsTablet.style.normal,
  },
  checkboxError: {
    color: 'red',
    backgroundColor: Colors.transparent,
    textAlign: 'left',
    marginTop: "-10@ms",
    ...FontsTablet.style.normal,
    fontSize: "12@ms",
    marginLeft: "20@ms",
    marginBottom: "10@ms",
  },
  sexError: {
    color: 'red',
    backgroundColor: Colors.transparent,
    textAlign: 'left',
    marginTop: "-5@vs",
    ...FontsTablet.style.normal,
    fontSize: "12@ms",
    marginLeft: "20@ms",
    marginBottom: "10@vs",
  },
  buttonView: {
    flex: 0.5,
    marginTop: "-10@vs",
    paddingTop: "10@vs",
    alignItems: 'stretch',
    width: '100%',
    alignSelf: 'center',
  },
  button: {
    position: 'absolute',
    bottom: 0,
    flex: 1,
    marginTop: "30@vs",
    width: '100%',
    height: "50@vs",
    alignSelf: 'center',
    borderRadius: 0,
    borderBottomLeftRadius:"5@ms",
    borderBottomRightRadius: "5@ms",
    borderWidth: 0,
  },
  cond: {
    color: Colors.main,
    paddingBottom: "10@vs",
    marginLeft: "10@ms",
  },
  cond2: {
    color: Colors.main,
    marginLeft: "10@ms",
  },
  submitBtn: {
    width: '100%',
    alignSelf: 'center',
    marginTop: "20@vs",
    height: Metricstablet.button,
  },
  loginIcon: {
    paddingTop:" 8@vs",
    paddingStart: "20@ms",
  },
  fullScreenFlex: {
    flex: 1,
  },
  linkText: {
    color: Colors.greyScaleSix,
    left: "8@vs",
    textTransform: 'uppercase',
    ...FontsTablet.style.buttonText,
  },
});