export enum Route {
  Root = 'Root',
  Start = 'Start',
  Login = 'Login',
  ResetPassword = 'ResetPassword',
  Register = 'Register',
  Dashboard = 'Dashboard',
  SelectStoryType = 'SelectStoryType',
  ConfirmUploadStory = 'ConfirmUploadStory',
  PerfumeDetails = 'PerfumeDetails',
  Perfumes = 'Perfumes',
  SaveRecipe = 'SaveRecipe',
  Onboarding = 'Onboarding',
  Selections = 'Selections',
  PersonalizedRecipeNoteSelection = 'PersonalizedRecipeNoteSelection',
  PersonalizedRecipeRecommendedPerfumes = 'PersonalizedRecipeRecommendedPerfumes',
  NoteSelection = 'NoteSelection',
  AddNote = 'AddNote',
  RecordVideo = 'RecordVideo',
  RecordAudio = 'RecordAudio',
  StoryPlayer = 'StroryPlayer',
  TextStory = 'TextStory',
  MyCollection = 'MyCollection',
  Search = 'Search',
  Profile = 'Profile',
  Cgu = 'Cgu',
}
